FROM node:18-alpine3.17 as build

WORKDIR /app
COPY . /app

RUN npm install
RUN npm run build

# Étape 2 : Servir avec Nginx
FROM nginx:stable-alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /var/www/html/

# Substituer $PORT avec la valeur fournie par Heroku
RUN sed -i "s/\$PORT/3000/g" /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
